apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service-{{ .Values.context }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
  {{- if .Values.release }}
    meta.helm.sh/release-name: {{ .Values.release }}
  {{- end }}
  {{- if .Values.namespace }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /api{{ .Values.ingress.path }}/?(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.context }}-srv
                port:
                  number: {{ .Values.port }}
    {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host }}
    {{- end }}
